[tool.poetry]
name = "x402-hpke"
version = "0.1.0a1"
description = "Provider-agnostic HPKE envelope for the x402 spec. A utility for confidential, verifiable payment requests and receipts across untrusted intermediaries, using canonical AAD, optional sidecar projection, and cross-language (Python/Node) interoperability."
authors = ["Tim Cotten <tcotten@scrypted.ai>"]
license = "MIT"
readme = "README.md"
packages = [{ include = "x402_hpke" }]
homepage = "https://scrypted.ai"
repository = "https://github.com/scryptedai/x402-hpke"
documentation = "https://github.com/scryptedai/x402-hpke/tree/main/docs"
keywords = ["hpke", "aead", "x25519", "jwks", "envelope"]
classifiers = [
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3.12",
  "License :: OSI Approved :: MIT License",
  "Development Status :: 3 - Alpha",
  "Topic :: Security :: Cryptography",
]

[tool.poetry.dependencies]
python = ">=3.12"
PyNaCl = "^1.5.0"
requests = "^2.32.3"

[tool.poetry.group.dev.dependencies]
pytest = "^8.3.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
